<?php

return [
    '_PATIENT_FIREBASE_TOPIC' => '_PATIENT_TOPIC',

    'SOCIAL_SIGNUP_FACEBOOK' => 1,
    'SOCIAL_SIGNUP_GOOGLE' => 2,
    'SOCIAL_SIGNUP_APPLE' => 3,

    'PATIENT_ENTITY_ID' => 1
];
